### ISSUE TITLE
[iOS] 4번째 리뷰 반영

### ISSUE THREAD

**Issue by Hansolkkim** [bugpigg/issue-tracker#39]
### 📙 작업 내역

- [x] CollectionView DataSource의 numberOfSections 제거 (default로 1을 반환함)
- [x] 오타 수정
- [x] ~Managable 객체에서 `setURLSession(_:)` 메서드 제거
- [x] issueIteam의 `darkMode` -> `isDarkMode` rename
- [ ] NetworkTarget들을 재사용가능하도록 수정해보기 (아직 모르겠음)
- [x] DataSource 객체에서 ViewModel 인스턴스가 아닌 Observable 타입 변수를 프로퍼티로 가지고 있도록 수정
- [x] EditingIssueManagable의 `idData` 속성 네이밍 수정
### 📘 작업 유형

- 리펙토링

### 📝 Issue 특이 사항

<br/><br/>

**Comment by Hansolkkim** [comment]
Jason!
[여기](https://github.com/codesquad-members-2022/issue-tracker/pull/199#discussion_r906908551)에 말씀하신 부분에서,
darkMode <-> isDarkMode 자리가 바뀌었어요!

**Comment by JasonLee0223** [comment]
앗.. 감사합니다!! 반영해서 푸쉬하였습니다! ㅠㅠ
