### ISSUE TITLE
[iOS] 1번째 리뷰 반영

### ISSUE THREAD

**Issue by Hansolkkim** [bugpigg/issue-tracker#4]
### 📙 작업 내역
- Sol
- [x] SceneDelegate의 `requestAccessToken(with: String)` 메소드 뎁스 줄이기
- [x] SignInManager로 부터 네트워크 로직 분리하기
- [x] SignInManager를 프로퍼티로 선언한 부분 제거
- [x] 로그인 과정에서 에러 처리하는 로직 구현
- Jason
- [x] struct으로 선언한 IssueItem 파일 새로 생성하여 DataSource로 부터 분리
- [x] IssueItem private로 Access control 수정
- [x] OOP에 맞춰서 3개 이상의 Swift 기본 데이터타입 프로퍼티를 가진 타입 구현 X
- [x] Cell에 구현한 title, issueDescription 중복 코드 줄이기
- [x] Left / Right 버튼 중복 코드 합치기
- [x] TabBar에 컨트롤러 선언 이유

### 📘 작업 유형
- 리펙토링

### 📝 Issue 특이 사항

<br/><br/>

**Comment by JasonLee0223** [comment]
OOP에 맞춰서 3개 이상의 Swift 기본 데이터타입 프로퍼티를 가진 타입 구현 X
-> 앞으로 모델이 커지면서 객체를 생성할 때 3개 이상의 기본 데이터타입 프로퍼티를 가진 타입으로 구현하지 않기!

**Comment by JasonLee0223** [comment]
리뷰어로 부터 Merge되어 Close하겠습니다!
